os: Visual Studio 2015

# Version format
version: 1.0.0.{build}

cache:
  - Source\packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop
    #- master

test: 
    assemblies:
    - '**\Our.Umbraco.Nexu.*.Tests.dll'

build_script:
  - cd Packaging
  - build-appveyor.bat

artifacts:
  - path: Packaging\Package\*.nupkg
  - path: Packaging\Package\*.zip
  
  
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/dawoe-umbraco/api/v2/package
    api_key:
      secure: xuhyqGpLpjeK0tUansB6IVWy89Fw+yqGqCmCpVuAY1fnDjfYrxA/gVGNBh8oU0JA
    artifact: /.*\.nupkg/
    on:
      branch: develop

