os: Visual Studio 2015

# Version format
version: 1.0.0.{build}

cache:
  - Source\packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop
    #- master

test: 
    assemblies:
    - '**\Our.Umbraco.Nexu.*.Tests.dll'

build_script:
  - cd Packaging
  - build.bat

artifacts:
  - path: Packaging\Package\*.nupkg
  - path: Packaging\Package\*.zip


